"""Initial migration

Revision ID: 9010f33c1603
Revises: 
Create Date: 2026-09-16 13:12:19.180715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9010f33c1603'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('objective', sa.String(length=255), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=False),
    sa.Column('cta', sa.String(length=255), nullable=False),
    sa.Column('reference_image_url', sa.Text(), nullable=True),
    sa.Column('verified_claims', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.Enum('draft', 'researching', 'awaiting_angle_selection', 'generating_spec', 'generating_assets', 'completed', 'completed_with_errors', 'failed', name='campaign_status'), server_default='draft', nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=255), nullable=True),
    sa.Column('temporal_run_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('temporal_workflow_id', name=op.f('uq_campaigns_temporal_workflow_id'))
    )
    op.create_table('research_runs',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='research_run_status'), server_default='running', nullable=False),
    sa.Column('tool_call_budget', sa.Integer(), nullable=False),
    sa.Column('tool_calls_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mock_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_runs'))
    )
    op.create_index('idx_research_runs_campaign_id', 'research_runs', ['campaign_id'], unique=False)
    op.create_table('creative_angles',
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('angle_number', sa.SmallInteger(), nullable=False),
    sa.Column('audience_insight', sa.Text(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('visual_direction', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('angle_number BETWEEN 1 AND 3', name=op.f('ck_creative_angles_ck_creative_angles_angle_number')),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], name=op.f('fk_creative_angles_research_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creative_angles')),
    sa.UniqueConstraint('research_run_id', 'angle_number', name='uq_creative_angles_run_number')
    )
    op.create_index('idx_creative_angles_one_selected', 'creative_angles', ['research_run_id'], unique=True, postgresql_where=sa.text('is_selected'))
    op.create_table('provider_usage',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('units', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_provider_usage_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_usage'))
    )
    op.create_index(op.f('ix_provider_usage_campaign_id'), 'provider_usage', ['campaign_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], name=op.f('fk_research_sources_research_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sources')),
    sa.UniqueConstraint('research_run_id', 'url', name='uq_research_sources_run_url')
    )
    op.create_index('idx_research_sources_run_id', 'research_sources', ['research_run_id'], unique=False)
    op.create_table('research_steps',
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('search', 'read_page', 'decide', name='research_step_type'), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], name=op.f('fk_research_steps_research_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_steps')),
    sa.UniqueConstraint('research_run_id', 'step_number', name='uq_research_steps_run_step')
    )
    op.create_index('idx_research_steps_run_id', 'research_steps', ['research_run_id'], unique=False)
    op.create_table('stage_events',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.Enum('research', 'angle_selection', 'spec_generation', 'hero_image', 'compose_1x1', 'compose_9x16', 'render_video', name='stage_name'), nullable=False),
    sa.Column('event_type', sa.Enum('started', 'completed', 'failed', 'retried', name='stage_event_type'), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_stage_events_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_events'))
    )
    op.create_index(op.f('ix_stage_events_campaign_id'), 'stage_events', ['campaign_id'], unique=False)
    op.create_table('angle_sources',
    sa.Column('angle_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['angle_id'], ['creative_angles.id'], name=op.f('fk_angle_sources_angle_id_creative_angles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], name=op.f('fk_angle_sources_source_id_research_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('angle_id', 'source_id', name=op.f('pk_angle_sources'))
    )
    op.create_table('creative_specs',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('angle_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('approved_copy', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('product_identity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scene_description', sa.Text(), nullable=False),
    sa.Column('palette', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('composition_guidance', sa.Text(), nullable=False),
    sa.Column('video_outline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['angle_id'], ['creative_angles.id'], name=op.f('fk_creative_specs_angle_id_creative_angles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creative_specs')),
    sa.UniqueConstraint('campaign_id', 'version', name='uq_creative_specs_campaign_version')
    )
    op.create_index('idx_creative_specs_campaign_id', 'creative_specs', ['campaign_id'], unique=False)
    op.create_table('assets',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('creative_spec_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('hero_image', 'ad_1x1', 'ad_9x16', 'video', name='asset_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'generating', 'completed', 'failed', name='asset_status'), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creative_spec_id'], ['creative_specs.id'], name=op.f('fk_assets_creative_spec_id_creative_specs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('campaign_id', 'asset_type', name='uq_assets_campaign_id_asset_type'),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_assets_idempotency_key'))
    )
    op.create_table('asset_generation_attempts',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('succeeded', 'failed', name='attempt_status'), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_generation_attempts_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_generation_attempts')),
    sa.UniqueConstraint('asset_id', 'attempt_number', name='uq_attempts_asset_id_attempt_number')
    )
    op.create_index('idx_asset_attempts_asset_id', 'asset_generation_attempts', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_asset_attempts_asset_id', table_name='asset_generation_attempts')
    op.drop_table('asset_generation_attempts')
    op.drop_table('assets')
    op.drop_index('idx_creative_specs_campaign_id', table_name='creative_specs')
    op.drop_table('creative_specs')
    op.drop_table('angle_sources')
    op.drop_index(op.f('ix_stage_events_campaign_id'), table_name='stage_events')
    op.drop_table('stage_events')
    op.drop_index('idx_research_steps_run_id', table_name='research_steps')
    op.drop_table('research_steps')
    op.drop_index('idx_research_sources_run_id', table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_provider_usage_campaign_id'), table_name='provider_usage')
    op.drop_table('provider_usage')
    op.drop_index('idx_creative_angles_one_selected', table_name='creative_angles', postgresql_where=sa.text('is_selected'))
    op.drop_table('creative_angles')
    op.drop_index('idx_research_runs_campaign_id', table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
